name: el_profe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #ui
  cupertino_icons: ^0.1.2

  #local data
  shared_preferences: ^0.5.6+3
  
  #code
  image: ^2.1.12
  shimmer: ^1.0.0
  photo_view: ^0.9.2
  image_picker: ^0.6.5
  carousel_slider: ^1.4.1
  cached_network_image: 2.0.0-rc
  flutter_advanced_networkimage: ^0.7.0
  flutter_cupertino_date_picker: ^1.0.12
  
  #firebase
  firebase_auth: ^0.15.1
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.12.11
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
